In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

%matplotlib inline

In [2]:
aepsi_data = pd.read_excel('../data/AEPSi Data for NSS.xlsx',2)
aepsi_data

,Child ID,Program Name,AEPSi ID,AssessID,State,Child First,Child Last,DOB,Gender,Dev Status,...,Adapt Result,Cog Goal Score,Cog Cutoff,Cog Result,SC Goal Score,SC Cutoff,SC Result,Soc Goal Score,Soc Cutoff,Soc Result
0,11,Signal Centers,722747,10584304,TN,XXXXXX,XXXXXX,2020-02-02 00:00:00,M,Dev. Delay or Disability,...,above,17.0,20.0,below,11.0,13.0,below,9.0,9.0,below
1,10724,Little Tennessee Valley Educational Cooperative,707878,10575064,TN,XXXXXX,XXXXXX,2021-07-30 00:00:00,F,Dev. Delay or Disability,...,above,3.0,4.0,below,2.0,3.0,below,0.0,1.0,below
2,10724,Little Tennessee Valley Educational Cooperative,707878,10589703,TN,XXXXXX,XXXXXX,2021-07-30 00:00:00,F,Dev. Delay or Disability,...,above,5.0,4.0,above,3.0,3.0,below,2.0,1.0,above
3,11112,SRVS,665041,10535282,TN,XXXXXX,XXXXXX,2020-04-27 00:00:00,F,Dev. Delay or Disability,...,below,8.0,7.5,above,7.0,5.0,above,7.0,4.0,above
4,11112,SRVS,665041,10503223,TN,XXXXXX,XXXXXX,2020-04-27 00:00:00,F,Dev. Delay or Disability,...,below,5.0,4.0,above,5.0,3.0,above,5.0,1.0,above
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17954,NaN,Porter Leath,528914,10224622,TN,XXXXXX,XXXXXX,2016-05-04 00:00:00,F,Dev. Delay or Disability,...,below,1.0,4.0,below,1.0,3.0,below,1.0,1.0,below
17955,NaN,Porter Leath,528913,10222226,TN,XXXXXX,XXXXXX,2016-05-04 00:00:00,F,Dev. Delay or Disability,...,below,0.0,1.0,below,2.0,0.0,above,0.0,0.0,below
17956,NaN,Porter Leath,528913,10224623,TN,XXXXXX,XXXXXX,2016-05-04 00:00:00,F,Dev. Delay or Disability,...,below,0.0,4.0,below,3.0,3.0,below,2.0,1.0,above
17957,NaN,Porter Leath,532226,10231183,TN,XXXXXX,XXXXXX,########,M,Dev. Delay or Disability,...,below,0.0,7.5,below,3.0,5.0,below,0.0,4.0,below
17958,NaN,Porter Leath,532787,10232713,TN,XXXXXX,XXXXXX,########,M,Dev. Delay or Disability,...,below,14.0,29.0,below,7.0,15.5,below,7.0,10.0,below

In [3]:
aeps_17_20 = aepsi_data.loc[:,['Child ID', 'Program Name', 'AEPSi ID','AssessID','DOB','Gender','Dev Status','AEPS Level','Test Date','Examiner','Chron Age','Service Coordinator','TEIS Point of Entry Office (POE)','ESL','County of Residence','fm_B4.0',
'fm_B5.0','cog_D2.0','cog_E2.0','cog_E4.0','cog_F1.0','cog_G1.0','cog_G2.0','cog_G3.0','cog_G4.0','cog_G5.0','cog_G6.0','sc_B1.0','sc_B2.0','sc_D1.0','sc_D2.0','sc_D3.0','FM Possible Score','Cog Possible Score','SC Possible Score']]

In [4]:
aeps_17_20

,Child ID,Program Name,AEPSi ID,AssessID,DOB,Gender,Dev Status,AEPS Level,Test Date,Examiner,...,cog_G5.0,cog_G6.0,sc_B1.0,sc_B2.0,sc_D1.0,sc_D2.0,sc_D3.0,FM Possible Score,Cog Possible Score,SC Possible Score
0,11,Signal Centers,722747,10584304,2020-02-02 00:00:00,M,Dev. Delay or Disability,1,2022-04-21 00:00:00,Maria E. Vives-Rodriguez,...,1.0,0.0,2.0,2.0,1.0,0.0,0.0,66.0,116.0,92.0
1,10724,Little Tennessee Valley Educational Cooperative,707878,10575064,2021-07-30 00:00:00,F,Dev. Delay or Disability,1,2022-03-01 00:00:00,Olivia J Woodall;Olivia Woodall,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
2,10724,Little Tennessee Valley Educational Cooperative,707878,10589703,2021-07-30 00:00:00,F,Dev. Delay or Disability,1,2022-05-09 00:00:00,Olivia J Woodall;Olivia Woodall,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
3,11112,SRVS,665041,10535282,2020-04-27 00:00:00,F,Dev. Delay or Disability,1,2021-07-08 00:00:00,Beth Murphree,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
4,11112,SRVS,665041,10503223,2020-04-27 00:00:00,F,Dev. Delay or Disability,1,2020-12-30 00:00:00,Beth Murphree,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17954,NaN,Porter Leath,528914,10224622,2016-05-04 00:00:00,F,Dev. Delay or Disability,1,########,Stephanie Boyce,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
17955,NaN,Porter Leath,528913,10222226,2016-05-04 00:00:00,F,Dev. Delay or Disability,1,########,"Stephanie Boyce, M.Ed",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
17956,NaN,Porter Leath,528913,10224623,2016-05-04 00:00:00,F,Dev. Delay or Disability,1,########,Stephanie Boyce,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
17957,NaN,Porter Leath,532226,10231183,########,M,Dev. Delay or Disability,1,########,"Stephanie Boyce, M.Ed",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0,116.0,92.0
17958,NaN,Porter Leath,532787,10232713,########,M,Dev. Delay or Disability,1,########,"Stephanie Boyce, M.Ed",...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,66.0,116.0,92.0

In [5]:
eco_exit_20_21 = pd.read_excel('../data/AEPSi Data for NSS.xlsx',4)
eco_exit_20_21

,DISTRICT,CHILD_ID,ECO_Entry_DATE,Ent SOCIAL_SCALE,Ent KNOWLEDGE_SCALE,Ent APPROPRIATE_ACTION_SCALE,ECO_Exit_DATE,Exit SOCIAL_SCALE,Exit KNOWLEDGE_SCALE,Exit APPROPRIATE_ACTION_SCALE,...,OC2 - d,OC2 - e,OC2 Data Check,OC3 - a,OC3 - b,OC3 - c,OC3 - d,OC3 - e,OC3 Data Check,Days btw Initial and Exit
0,ET,456849,2019-04-24,3.0,5.0,7.0,2019-10-14,7.0,5.0,7.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,569.0
1,ET,490916,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,221.0
2,ET,426757,2019-03-13,2.0,3.0,4.0,2020-08-12,6.0,7.0,7.0,...,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1.0,533.0
3,ET,480611,2020-05-28,2.0,5.0,1.0,2020-11-09,5.0,6.0,3.0,...,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,298.0
4,ET,492863,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8443,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8444,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8445,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8446,NaN,Corrected Child ID 475887 impossible combinati...,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8447,NaN,Corrected Child ID 486516 impossible combinati...,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
eco_exit_21_22=pd.read_excel('../data/AEPSi Data for NSS.xlsx',6)
eco_exit_21_22

,DISTRICT,CHILD_ID,ECO_Entry_DATE,Ent SOCIAL_SCALE,Ent KNOWLEDGE_SCALE,Ent APPROPRIATE_ACTION_SCALE,ECO_Exit_DATE,Exit SOCIAL_SCALE,Exit KNOWLEDGE_SCALE,Exit APPROPRIATE_ACTION_SCALE,...,OC2 Data Check,OC3 - a,OC3 - b,OC3 - c,OC3 - d,OC3 - e,OC3 Data Check,Days btw Initial and Exit,Days btw I-IFSP to Exit ECO,Days btw I-IFSP to entry ECO
0,ET,500335.0,2021-04-23,5.0,3.0,4.0,2021-10-23,6.0,3.0,4.0,...,1.0,NaN,1.0,NaN,NaN,NaN,1.0,206.0,183.0,0.0
1,ET,479453.0,2020-03-23,7.0,7.0,7.0,2021-08-19,7.0,7.0,7.0,...,1.0,NaN,NaN,NaN,NaN,1.0,1.0,704.0,514.0,0.0
2,ET,510663.0,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,115.0,-44483.0,-44483.0
3,ET,452482.0,2019-01-31,2.0,3.0,3.0,2021-11-22,5.0,3.0,5.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1053.0,1026.0,0.0
4,ET,506507.0,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,159.0,-44434.0,-44434.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,UC,514216.0,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,65.0,-44537.0,-44537.0
8632,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8633,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8634,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8635,9/29/22 JM Corrected in TEIDS. Progress would ...,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
eco_exit_20_21_1=eco_exit_20_21.loc[:,['DISTRICT','CHILD_ID','ECO_Entry_DATE','Ent SOCIAL_SCALE','Ent KNOWLEDGE_SCALE','Ent APPROPRIATE_ACTION_SCALE','ECO_Exit_DATE','Exit SOCIAL_SCALE','Exit KNOWLEDGE_SCALE','Exit APPROPRIATE_ACTION_SCALE','Exit IS_SOCIAL_PROGRESS','Exit IS_KNOWLEDGE_PROGRESS','Exit IS_APPROPRIATE_ACTION_PROGRESS','DOB','Initial IFSP Date','Exit Reason','Exit Date',
'OC1 Data Check','OC2 Data Check','OC3 Data Check']]
eco_exit_20_21_1

,DISTRICT,CHILD_ID,ECO_Entry_DATE,Ent SOCIAL_SCALE,Ent KNOWLEDGE_SCALE,Ent APPROPRIATE_ACTION_SCALE,ECO_Exit_DATE,Exit SOCIAL_SCALE,Exit KNOWLEDGE_SCALE,Exit APPROPRIATE_ACTION_SCALE,Exit IS_SOCIAL_PROGRESS,Exit IS_KNOWLEDGE_PROGRESS,Exit IS_APPROPRIATE_ACTION_PROGRESS,DOB,Initial IFSP Date,Exit Reason,Exit Date,OC1 Data Check,OC2 Data Check,OC3 Data Check
0,ET,456849,2019-04-24,3.0,5.0,7.0,2019-10-14,7.0,5.0,7.0,Yes,Yes,Yes,2017-11-14,2019-04-24,618 - Part B eligible,2020-11-13,1.0,1.0,1.0
1,ET,490916,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-02,2020-11-02,618 - Parent withdraw,2021-06-11,0.0,0.0,0.0
2,ET,426757,2019-03-13,2.0,3.0,4.0,2020-08-12,6.0,7.0,7.0,Yes,Yes,Yes,2017-08-28,2019-03-13,618 - Part B eligibility not determined,2020-08-27,1.0,1.0,1.0
3,ET,480611,2020-05-28,2.0,5.0,1.0,2020-11-09,5.0,6.0,3.0,Yes,Yes,Yes,2019-11-29,2020-05-28,618 - Parent withdraw,2021-03-22,1.0,1.0,1.0
4,ET,492863,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-07,2020-12-02,618 - Parent withdraw,2021-04-28,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8443,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN
8444,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN
8445,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN
8446,NaN,Corrected Child ID 475887 impossible combinati...,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN
8447,NaN,Corrected Child ID 486516 impossible combinati...,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN

In [9]:
eco_exit_21_22_2= eco_exit_21_22.loc[:,['DISTRICT','CHILD_ID','ECO_Entry_DATE','Ent SOCIAL_SCALE','Ent KNOWLEDGE_SCALE','Ent APPROPRIATE_ACTION_SCALE','ECO_Exit_DATE','Exit SOCIAL_SCALE','Exit KNOWLEDGE_SCALE','Exit APPROPRIATE_ACTION_SCALE','ExitIS_SOCIAL_PROGRESS','ExitIS_KNOWLEDGE_PROGRESS','ExitIS_APPROPRIATE_ACTION_PROGRESS','Initial IFSP Date','Exit Reason','Exit Date','OC1 Data Check','OC2 Data Check','OC3 Data Check'
]]
eco_exit_21_22_2

,DISTRICT,CHILD_ID,ECO_Entry_DATE,Ent SOCIAL_SCALE,Ent KNOWLEDGE_SCALE,Ent APPROPRIATE_ACTION_SCALE,ECO_Exit_DATE,Exit SOCIAL_SCALE,Exit KNOWLEDGE_SCALE,Exit APPROPRIATE_ACTION_SCALE,ExitIS_SOCIAL_PROGRESS,ExitIS_KNOWLEDGE_PROGRESS,ExitIS_APPROPRIATE_ACTION_PROGRESS,Initial IFSP Date,Exit Reason,Exit Date,OC1 Data Check,OC2 Data Check,OC3 Data Check
0,ET,500335.0,2021-04-23,5.0,3.0,4.0,2021-10-23,6.0,3.0,4.0,Yes,Yes,Yes,2021-04-23,618 - Part B eligible,2021-11-15,1.0,1.0,1.0
1,ET,479453.0,2020-03-23,7.0,7.0,7.0,2021-08-19,7.0,7.0,7.0,Yes,Yes,Yes,2020-03-23,618 - Completion of IFSP/ no longer requires s...,2022-02-25,1.0,1.0,1.0
2,ET,510663.0,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-14,618 - Part B eligible,2022-02-06,0.0,0.0,0.0
3,ET,452482.0,2019-01-31,2.0,3.0,3.0,2021-11-22,5.0,3.0,5.0,Yes,Yes,Yes,2019-01-31,618 - Part B eligible,2021-12-19,1.0,1.0,1.0
4,ET,506507.0,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-26,618 - Parent withdraw,2022-02-01,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,UC,514216.0,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-07,618 - Parent withdraw,2022-02-10,0.0,0.0,0.0
8632,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
8633,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
8634,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
8635,9/29/22 JM Corrected in TEIDS. Progress would ...,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN